#!/usr/bin/env bash

if [[ -z "$PORT" ]]
then
    PORT=`poetry run python -m portpicker $$`
else
    PORT=$PORT
fi

poetry run uvicorn crypto_market_trader.main:create_app --port $PORT --factory --reload
unset PORT

